-- Add migration script here
USE sunminimart;

CREATE TABLE IF NOT EXISTS products (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Barcode VARCHAR(64) UNIQUE NOT NULL,
    Name VARCHAR(64) NOT NULL,
    Price SMALLINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS stocks (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Barcode VARCHAR(64) NOT NULL,
    Cost DECIMAL(5, 2) NOT NULL,
    Amount SMALLINT UNSIGNED NOT NULL,
    FOREIGN KEY (Barcode) REFERENCES products(Barcode) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS expire_dates (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Barcode VARCHAR(64) NOT NULL,
    ExpireDate DATE NOT NULL,
    FOREIGN KEY (Barcode) REFERENCES products(Barcode) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ledger (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    Barcode VARCHAR(64) NOT NULL,
    Name VARCHAR(64) NOT NULL,
    Cost DECIMAL(5, 2) NOT NULL,
    Price  SMALLINT UNSIGNED NOT NULL,
    Amount SMALLINT UNSIGNED NOT NULL,
    Profit DECIMAL(5, 2) NOT NULL,
    VAT DECIMAL(5, 2) NOT NULL
);
